---
# Rol ACR - Gestión de imágenes de contenedores
- name: Login to Azure Container Registry
  containers.podman.podman_login:
    username: "{{ acr_username }}"
    password: "{{ acr_password }}"
    registry: "{{ acr_login_server }}"

- name: Pull images from Docker Hub
  containers.podman.podman_image:
    name: "{{ item.source }}"
    state: present
  loop: "{{ container_images }}"

- name: Tag images for ACR
  containers.podman.podman_tag:
    image: "{{ item.source }}"
    target_names: "{{ acr_login_server }}/{{ item.target }}"
  loop: "{{ container_images }}"

- name: Push images to ACR
  containers.podman.podman_image:
    name: "{{ acr_login_server }}/{{ item.target }}"
    push: yes
    username: "{{ acr_username }}"
    password: "{{ acr_password }}"
  loop: "{{ container_images }}"