---
# roles/vm/tasks/main.yml
- import_tasks: setup.yml
- import_tasks: auth.yml
- import_tasks: webcontent.yml
- import_tasks: container.yml


# Rol VM - Configuración de la máquina virtual
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install required packages
  apt:
    name: 
      - podman
      - python3-pip
      - apache2-utils
    state: present
  become: yes

- name: Login to ACR from VM
  containers.podman.podman_login:
    username: "{{ acr_username }}"
    password: "{{ acr_password }}"
    registry: "{{ acr_login_server }}"
  no_log: true # Evitar que las credenciales de ACR aparezcan en los logs de Ansible

- name: Create volume directory
  file:
    path: "{{ web_content_dir }}"
    state: directory
    mode: '0755'
  become: yes

- name: Create htpasswd file
  community.general.htpasswd:
    path: /data/webserver/.htpasswd
    name: "{{ htpasswd_user }}"
    password: "{{ htpasswd_pass }}"
    crypt_scheme: md5

- name: Create a sample index.html
  become: yes
  ansible.builtin.copy:
    dest: /data/webserver/index.html
    content: "<h1>¡Hola desde Podman + Nginx!</h1>"

- name: Run nginx container
  containers.podman.podman_container:
    name: webserver
    image: "{{ acr_login_server }}/nginx:latest"
    state: started
    ports:
      - "8080:80"
    volumes:
      - /data/webserver:/usr/share/nginx/html
    restart_policy: always
